print("hello")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")
print("The code is updated")